export const HERO_ITEMS = [
  require("../../../../assets/images/Home/hero_gallery/first.png"),
  require("../../../../assets/images/Home/hero_gallery/second.png"),
  require("../../../../assets/images/Home/hero_gallery/third.png"),
];

import { type Job } from "./components/JobCard";

export const INITIAL_JOBS: Job[] = [
  {
    id: "1",
    title: "Tile Mason",
    location: "Andheri East, Mumbai",
    joiningDate: "26 Feb 2026, 7:00 AM",
    mapUrl: "https://maps.google.com/?q=Andheri+East+Mumbai",
    payLabel: "\u20B91,200 per day",
  },
  {
    id: "2",
    title: "Warehouse Helper",
    location: "Bhiwandi, Thane",
    joiningDate: "26 Feb 2026, 2:30 PM",
    mapUrl: "https://maps.google.com/?q=Bhiwandi+Thane",
    payLabel: "\u20B9900 per shift",
  },
  {
    id: "3",
    title: "House Painter",
    location: "Whitefield, Bengaluru",
    joiningDate: "27 Feb 2026, 8:00 AM",
    mapUrl: "https://maps.google.com/?q=Whitefield+Bengaluru",
    payLabel: "\u20B91,400 per day",
  },
  {
    id: "4",
    title: "Delivery Rider",
    location: "Baner, Pune",
    joiningDate: "27 Feb 2026, 10:00 AM",
    mapUrl: "https://maps.google.com/?q=Baner+Pune",
    payLabel: "\u20B9800 per shift",
  },
  {
    id: "5",
    title: "Electrician Assistant",
    location: "Anna Nagar, Chennai",
    joiningDate: "27 Feb 2026, 9:30 AM",
    mapUrl: "https://maps.google.com/?q=Anna+Nagar+Chennai",
    payLabel: "\u20B91,100 per day",
  },
  {
    id: "6",
    title: "Carpenter",
    location: "Madhapur, Hyderabad",
    joiningDate: "28 Feb 2026, 8:30 AM",
    mapUrl: "https://maps.google.com/?q=Madhapur+Hyderabad",
    payLabel: "\u20B91,500 per day",
  },
  {
    id: "7",
    title: "Store Loader",
    location: "Salt Lake, Kolkata",
    joiningDate: "28 Feb 2026, 6:00 AM",
    mapUrl: "https://maps.google.com/?q=Salt+Lake+Kolkata",
    payLabel: "\u20B9850 per shift",
  },
  {
    id: "8",
    title: "Plumber",
    location: "Alkapuri, Vadodara",
    joiningDate: "28 Feb 2026, 11:00 AM",
    mapUrl: "https://maps.google.com/?q=Alkapuri+Vadodara",
    payLabel: "\u20B91,300 per day",
  },
  {
    id: "9",
    title: "Kitchen Helper",
    location: "Sector 18, Noida",
    joiningDate: "1 Mar 2026, 1:00 PM",
    mapUrl: "https://maps.google.com/?q=Sector+18+Noida",
    payLabel: "\u20B9750 per shift",
  },
  {
    id: "10",
    title: "Security Guard",
    location: "Dwarka, New Delhi",
    joiningDate: "1 Mar 2026, 7:00 PM",
    mapUrl: "https://maps.google.com/?q=Dwarka+New+Delhi",
    payLabel: "\u20B91,000 per shift",
  },
];
